# Generated by Django 2.0.5 on 2020-01-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='updated_date',
            field=models.DateField(null=True),
        ),
    ]
