# Generated by Django 2.0.5 on 2020-01-02 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0002_auto_20200102_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='updated_date',
        ),
    ]
